### ISSUE TITLE
[TO-DO] Todo list for 2.0.0B (Actual is in 1.*.*A)

### ISSUE THREAD

**Issue by TheKillerTacos** [TheKillerTacos/PermList#1]
Todo list before the 2.0.0B Release (actual is 1.*.*A)

- [ ] Save Permissions on TXT files

- [ ] Save Perms separated (Op & default)

- [ ] Less JunkCode

- [ ] PHP7

- [ ] 2.0.0API support

- [ ] MultiLanguage Support (might not be needed at all)

and more!
